### ISSUE TITLE
niveristand-instrument-addon-custom-device

### ISSUE THREAD

**Issue by momo815** [ni/niveristand-instrument-addon-custom-device#191] opened 2021-11-12 05:47 UTC
When  the three codes were opened with lv2020 , NationalInstruments.VeriStand.SystemDefinitionAPI and VeriStandTestCase couldn't be loaded normally.

codes
![Uploading three codes.PNG…]()
 :

**Comment by momo815** [comment] 2021-11-12 05:49
The three codes were 
niveristand-custom-device-testing-tools-main,
niveristand-instrument-addon-classes-main,
niveristand-instrument-addon-custom-device-20.5.0.

**Comment by phutanu** [comment] 2021-11-12 07:24
Hi @momo815,

Thanks for reporting this.

Please use one of the provided issue templates in order to help us understand and try to reproduce the issue:
![image](https://user-images.githubusercontent.com/62251693/141426910-c452906d-9320-48d1-acd3-fd025357511b.png)

Thanks,
Paul

**Comment by phutanu** [comment] 2021-11-12 07:27
One thing you can check is that you have all the [Source Dependencies](https://github.com/ni/niveristand-instrument-addon-custom-device#source) listed in the Instrument Addon Readme.md.

**Comment by phutanu** [comment] 2021-11-17 06:44
@momo815 Closing this as it is a duplicate of #192.

**Closed by phutanu** 2021-11-17 06:44 UTC
