### ISSUE TITLE
Error Code clears when a message is triggered; error code is always zero when msg is set for periodic

### ISSUE THREAD

**Issue by labviewmantc** [ni/niveristand-instrument-addon-custom-device#177] opened 2021-05-06 11:07 UTC
I have only used the AK-TCP portion of the driver.

1) When a send msg is triggered via script or with a front-panel object (or likely ever), the current value of the error-code is cleared, then sends the msg/processes the response, then updates the error code.
-seems this error-code should only update when the operation is complete

2) When a send msg is set for periodic, the error code is always zero
-maybe always show the latest error-code only (error code as the result of the last operation)

**Comment by csteavu** [comment] 2021-05-06 11:55
Hello @labviewmantc,

We'll take a look at this issue.

**Comment by phutanu** [comment] 2021-05-17 12:57
Hello @labviewmantc,

I tested the behaviors mentioned above using the latest release.

> 1. When a send msg is triggered via script or with a front-panel object (or likely ever), the current value of the error-code is cleared, then sends the msg/processes the response, then updates the error code.
-seems this error-code should only update when the operation is complete

This behavior is intended and the Error Code Channel works as expected.

> 2. When a send msg is set for periodic, the error code is always zero
-maybe always show the latest error-code only (error code as the result of the last operation)

I used a Command-Response Message setup and the Error Code Channel is set to a value different than 0 in case of errors even when the Message is of  'Periodic & Trigger' type.

I will close this issue as we think the channels work as intended.

If you still think there is an issue with the Error Code Channel, please feel free to re-open this issue and add more specific details to the behavior you are referring to.

**Closed by phutanu** 2021-05-17 12:57 UTC

**Comment by labviewmantc** [comment] 2021-05-18 10:13
1) Let's agree to disagree. The output "Error Code" is and output...an output should not update until the operation is complete...to update an output before the operation is complete makes no sense at all.  I've never seen a LabVIEW or C function return a result BEFORE the operation is complete, so why does this?

2) Also we will have to agree to disagree on the error code always equal to 0 when the message is set to periodic.  The Error code should be the result of the last operation...period. Not cleared when the operation starts, not cleared when the operation is in progress, but rather the end result of the last operation...period. To operate otherwise just makes no sense.

**Comment by phutanu** [comment] 2021-05-21 12:12
Hello @labviewmantc,

We made the following change (#181) that will make the Error Code channel update only at the end of an operation. Should be read only when Message Status is '1'.
